Repository cau-overchaos/bidrum, pull requests merged in 2024-04, with the labels that each got.

#20 docs: change typo of step3 of How to build of MAC
  README.md
Labels: documentation

#21 chore: change Cargo.toml dependencies version
  Cargo.lock
  game/Cargo.toml
Labels: bug, dependencies

#23 Bid 46 score and health calculate logic
  game/src/game/display_result.rs
  game/src/game/game_player/game_result.rs
  game/src/game/game_player/timing_judge.rs
Labels: enhancement
